// Static pre-crawled index of all Codeforces blogs, served as chunked JSON
// from /blog-index/ (generated by scripts/build-blog-index.mjs). Lets the feed
// find older unseen blogs instantly instead of probing the API id-by-id.
let manifestPromise = null
const chunkCache = new Map()

function getManifest() {
  if (!manifestPromise) {
    manifestPromise = fetch('/blog-index/manifest.json')
      .then((res) => (res.ok ? res.json() : null))
      .catch(() => null)
  }
  return manifestPromise
}

function getChunk(n, manifest) {
  if (!chunkCache.has(n)) {
    const promise = fetch(`/blog-index/chunk-${n}.json?v=${manifest.version}`)
      .then((res) => (res.ok ? res.json() : []))
      .catch(() => {
        chunkCache.delete(n)
        return []
      })
    chunkCache.set(n, promise)
  }
  return chunkCache.get(n)
}

// Id range [minId, maxId] covered by the index, or null if none is deployed.
// Blogs below minId exist but weren't crawled yet (partial index).
export async function indexRange() {
  const manifest = await getManifest()
  if (!manifest) return null
  return { maxId: manifest.maxId, minId: manifest.minId || 1 }
}

// Returns up to `count` indexed entries with id < beforeId, newest first,
// or null if no index is deployed.
export async function fetchIndexedOlderEntries(beforeId, count, shouldSkip) {
  const manifest = await getManifest()
  if (!manifest) return null
  const topChunk = Math.floor(manifest.maxId / manifest.chunkSize)
  const bottomChunk = Math.floor((manifest.minId || 1) / manifest.chunkSize)
  let chunk = Math.min(Math.floor((beforeId - 1) / manifest.chunkSize), topChunk)
  const entries = []
  while (entries.length < count && chunk >= bottomChunk) {
    const list = await getChunk(chunk, manifest)
    for (const e of list) {
      if (e.i >= beforeId || shouldSkip(e.i)) continue
      entries.push({
        id: e.i,
        title: e.t,
        authorHandle: e.a,
        rating: e.r,
        creationTimeSeconds: e.c,
        tags: e.g || [],
        url: `https://codeforces.com/blog/entry/${e.i}`,
      })
      if (entries.length === count) break
    }
    if (entries.length < count) chunk--
  }
  // When the walk exhausts the index, hand off at minId so uncrawled older
  // blogs (partial index) can still be discovered via the live API.
  const minId = manifest.minId || 1
  const nextBeforeId =
    entries.length === count ? entries[entries.length - 1].id : minId > 1 ? minId : 0
  return { entries, nextBeforeId }
}
